<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('clicker', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($questions as $question) : ?>
<tr>
    <td><?php echo $this->escapeHtml($question->name);?></td>
    <td><?php echo $this->escapeHtml($question->content);?></td>
    <td>
        <a href="<?php echo $this->url('clicker', array('action'=>'edit', 'id' => $question->id));?>">Edit</a>
        <a href="<?php echo $this->url('clicker', array('action'=>'delete', 'id' => $question->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
